# Generated by Django 5.1.4 on 2024-12-29 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='タイトル')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開予定日時')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開済み')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='引用元URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('comment_count', models.IntegerField(default=0, verbose_name='コメント数')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True, verbose_name='カテゴリー名')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleSnap.article', verbose_name='記事')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleSnap.category', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '記事カテゴリー関連',
                'verbose_name_plural': '記事カテゴリー関連',
                'db_table': 'article_categories',
                'unique_together': {('category', 'article')},
            },
        ),
    ]
