# Generated by Django 5.1.4 on 2025-01-01 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0003_media_comment_post_articlemedia_postmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.ManyToManyField(related_name='articles', to='ArticleSnap.media', verbose_name='関連メディア'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ArticleSnap.article', verbose_name='記事'),
        ),
        migrations.DeleteModel(
            name='ArticleMedia',
        ),
    ]
