# Generated by Django 5.1.4 on 2025-01-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0005_alter_postmedia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='ArticleSnap.category', verbose_name='関連カテゴリー'),
        ),
    ]
