# Generated by Django 5.1.4 on 2025-01-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0006_alter_category_options_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment_count',
        ),
    ]
