# Generated by Django 5.1.4 on 2025-01-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0007_alter_comment_options_remove_article_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='コメント数'),
        ),
    ]
