# Generated by Django 5.1.4 on 2025-01-01 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0008_article_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='depth',
            field=models.IntegerField(default=0, verbose_name='深さ'),
        ),
        migrations.AddField(
            model_name='post',
            name='parentid',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='親ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='thingid',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Thing ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
