# Generated by Django 5.1.4 on 2025-01-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleSnap', '0009_post_depth_post_parentid_post_thingid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_translated',
            field=models.TextField(blank=True, null=True, verbose_name='タイトル（日本語訳）'),
        ),
    ]
